name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Aplicar Terraform (com aprovação manual)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve

  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Substitua pela sua região

      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Destruir recursos com Terraform
        run: |
          terraform init
          terraform destroy -auto-approve
        working-directory: terraform/  # Ajuste para a pasta onde está o código do Terraform

      - name: Deletar um recurso AWS CLI (Exemplo EC2)
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=Terraform-EC2" --query "Reservations[*].Instances[*].InstanceId" --output text)
          if [ -n "$INSTANCE_ID" ]; then
            aws ec2 terminate-instances --instance-ids $INSTANCE_ID
          else
            echo "Nenhuma instância encontrada."
          fi